language: python
python:
    - "3.6"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/NumberPipeline.cpp
    # - PLATFORMIO_CI_SRC=examples/

install:
    - pip install -U platformio
    - platformio update

script:
    - platformio ci --lib="." --board=adafruit_feather_m0 --board=adafruit_grandcentral_m4