language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    # - PLATFORMIO_CI_SRC=examples/
    # - PLATFORMIO_CI_SRC=examples/

install:
    - pip install -U platformio
    - platformio update

script:
    - platformio ci --lib="." --board=adafruit_feather_m0 --board=uno --board=adafruit_grandcentral_m4